# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-05-07 04:33
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Attraction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=255)),
                ('subject_en', models.CharField(max_length=255, null=True)),
                ('subject_de', models.CharField(max_length=255, null=True)),
                ('subject_pt', models.CharField(max_length=255, null=True)),
                ('paragraph1', models.TextField(max_length=4000)),
                ('paragraph1_en', models.TextField(max_length=4000, null=True)),
                ('paragraph1_de', models.TextField(max_length=4000, null=True)),
                ('paragraph1_pt', models.TextField(max_length=4000, null=True)),
                ('paragraph2', models.TextField(max_length=4000)),
                ('paragraph2_en', models.TextField(max_length=4000, null=True)),
                ('paragraph2_de', models.TextField(max_length=4000, null=True)),
                ('paragraph2_pt', models.TextField(max_length=4000, null=True)),
                ('title', models.CharField(max_length=255)),
                ('title_en', models.CharField(max_length=255, null=True)),
                ('title_de', models.CharField(max_length=255, null=True)),
                ('title_pt', models.CharField(max_length=255, null=True)),
                ('last_updated', models.DateTimeField(auto_now_add=True)),
                ('views', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(max_length=4000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(null=True)),
                ('attraction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='counties.Attraction')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='County',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
                ('name_en', models.CharField(max_length=30, null=True, unique=True)),
                ('name_de', models.CharField(max_length=30, null=True, unique=True)),
                ('name_pt', models.CharField(max_length=30, null=True, unique=True)),
                ('description', models.CharField(max_length=100)),
                ('description_en', models.CharField(max_length=100, null=True)),
                ('description_de', models.CharField(max_length=100, null=True)),
                ('description_pt', models.CharField(max_length=100, null=True)),
                ('paragraph', models.TextField(max_length=1000)),
                ('paragraph_en', models.TextField(max_length=1000, null=True)),
                ('paragraph_de', models.TextField(max_length=1000, null=True)),
                ('paragraph_pt', models.TextField(max_length=1000, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='attraction',
            name='county',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attractions', to='counties.County'),
        ),
    ]
